### ISSUE TITLE
CSV::MalformedCSVError: Illegal quoting in line 1 when update

### ISSUE THREAD

**Issue by aalvarado** [jorgevaldivia/salesforce_bulk#25]
When trying to update records, it appears to work fine from the command line but when using it inside a rake task it fails when calling `get_batch_result`

Relevant stack trace

```
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1852:in `block (2 levels) in shift'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1814:in `each'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1814:in `block in shift'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1774:in `loop'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1774:in `shift'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1716:in `each'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1730:in `to_a'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1730:in `read'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/csv.rb:1291:in `parse'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/salesforce_bulk-1.0.3/lib/salesforce_bulk/job.rb:132:in `parse_results'
/home/adan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/salesforce_bulk-1.0.3/lib/salesforce_bulk/job.rb:123:in `get_batch_result'
```

**Comment by aalvarado** [comment]
I don't think this is relevant. closing.
